Repository DoITFronts/Frontend, pull requests merged in 2025-02, with the labels that each got.

#3 test: Jira 연동 테스트
  .gitignore
  .idea/workspace.xml
  components/ui/Chip.tsx
Labels: Feat

#4 SCRUM-9 husky, prettier 세팅 추가
  .husky/pre-commit
  .prettierrc.json
Labels: Feat

#7 [feat/setting/eslint/DOIT-15] lint, prettier, husky 추가
  .lintstagedrc.json
  .prettierrc.json
  package.json
  yarn.lock
Labels: Setting

#8 [Feat/setting/DOIT-14] lint, husky, prettier setting develop 브랜치에 머지
  .gitignore
  .lintstagedrc.json
  .prettierrc.json
  package.json
  yarn.lock
Labels: Setting

#9 [Feat/setting/eslint/DOIT-15] 린트, 프리티어 설정 변겅
  .husky/pre-commit
  .lintstagedrc.json
  .prettierrc.json
  eslint.config.mjs
  package.json
  prettier.config.js
Labels: Setting

#10 [Feat/setting/DOIT-14] 린트, 프리티어 확정
  .husky/pre-commit
  .lintstagedrc.json
  .prettierrc.json
  eslint.config.mjs
  package.json
  prettier.config.js
Labels: Setting

#11 [Feat/setting/DOIT-14] 테일윈드 글로벌 설정 추가
  tailwind.config.ts
  types/.gitkeep
Labels: Setting

#12 [Feat/component/chip/DOIT-38]
  .eslintrc.json
  app/mypage/.gitkeep
  app/mypage/page.tsx
  components/shared/.gitkeep
  components/shared/Icons/CheckIcon.tsx
  components/ui/.gitkeep
  components/ui/Chip.tsx
  components/ui/Tag.tsx
  components/ui/chip/Chip.tsx
  components/ui/chip/ChipInfo.tsx
  components/ui/chip/ChipState.tsx
  eslint.config.mjs
  package-lock.json
  package.json
Labels: Setting

#14 [Feat/component/box select/DOIT-42] Box-Select 컴포넌트 추가
  .eslintrc.json
  .gitignore
  .husky/pre-commit
  .lintstagedrc.json
  .prettierrc.json
  app/mypage/.gitkeep
  app/mypage/page.tsx
  components/shared/.gitkeep
  components/shared/Icons/CheckIcon.tsx
  components/ui/.gitkeep
  components/ui/BoxSelect.tsx
  components/ui/Chip.tsx
  components/ui/Tag.tsx
  components/ui/chip/Chip.tsx
  components/ui/chip/ChipInfo.tsx
  components/ui/chip/ChipState.tsx
  eslint.config.mjs
  package-lock.json
  package.json
  prettier.config.js
  styles/global.css
  styles/theme.ts
  tailwind.config.ts
  types/.gitkeep
  yarn.lock
Labels: Feat

#16 [Feat/component/profile/DOIT-41] 프로필 컴포넌트 구현
  app/mypage/components/PropfileCard.tsx
  app/mypage/page.tsx
  components/shared/Icon.tsx
  components/shared/Icons/EditIcon.tsx
  public/assets/profile/avatar.svg
  public/assets/profile/profileCardBg.svg
  styles/global.css
  tailwind.config.ts
  yarn.lock
Labels: Feat

#30 [feat/setting/layout/DOIT-46] Base layout setting (DOIT-46)
  .eslintrc.json
  app/chat/chatdetail/.gitkeep
  app/chat/chatdetail/page.tsx
  app/globals.css
  app/layout.tsx
  app/meeting/list/components/Card.tsx
  app/meeting/list/components/ConfirmedStatus.tsx
  app/meeting/list/components/DateDisplay.tsx
  app/meeting/list/components/Join.tsx
  app/meeting/list/components/Like.tsx
  app/meeting/list/components/Participant.tsx
  app/meeting/list/components/ProgressBar.tsx
  app/meeting/list/components/TimeDisplay.tsx
  app/meeting/list/components/Title.tsx
  app/mypage/.gitkeep
  app/mypage/components/PropfileCard.tsx
  app/mypage/page.tsx
  app/page.tsx
  app/user/login/.gitkeep
  app/user/login/page.tsx
  components/layout/.gitkeep
  components/layout/BottomFloatingBar.tsx
  components/layout/Gnb.tsx
  components/shared/.gitkeep
  components/shared/Icon.tsx
  components/shared/Icons/CheckIcon.tsx
  components/shared/Icons/EditIcon.tsx
  components/ui/.gitkeep
  components/ui/BoxSelect.tsx
  components/ui/Button.tsx
  components/ui/Chip.tsx
  components/ui/Tag.tsx
  components/ui/chip/Chip.tsx
  components/ui/chip/ChipInfo.tsx
  components/ui/chip/ChipState.tsx
  eslint.config.mjs
  next.config.ts
  package-lock.json
  package.json
  public/assets/profile/avatar.svg
  public/assets/profile/profileCardBg.svg
  styles/global.css
  styles/theme.ts
  tailwind.config.ts
  yarn.lock
Labels: setting

#31 [Feat/setting/doit 14] Base layout setting
  app/chat/chatdetail/.gitkeep
  app/chat/chatdetail/page.tsx
  app/globals.css
  app/layout.tsx
  app/page.tsx
  app/user/login/page.tsx
  components/layout/Gnb.tsx
  package.json
  styles/global.css
Labels: setting

#21 [feat/component/review/DOIT-49] HeartRatingIcon 추가
  components/shared/Icons/HeartRatingIcon.tsx
  public/assets/review/heart_empty.svg
  public/assets/review/heart_full.svg
Labels: feature, component

#20 [feat/component/modal/DOIT-23] Modal 컴포넌트
  app/globals.css
  app/layout.tsx
  components/ui/BoxSelect.tsx
  components/ui/modal/Modal.tsx
  components/ui/modal/datePicker/CustomInput.tsx
  components/ui/modal/datePicker/CustomTimeInput.tsx
  components/ui/modal/datePicker/index.tsx
  components/ui/modal/variants/CreateMeetingModal.tsx
  components/ui/modal/variants/ProfileModal.tsx
  components/ui/modal/variants/SignUpModal.tsx
  package-lock.json
  package.json
  public/assets/X.svg
  public/assets/profile/editAvatar.svg
  public/calendar.svg
  store/useModalStore.ts
Labels: feature, component

#18 [Feat/component/pagination/DOIT-47] Pagination 컴포넌트 추가
  app/mypage/page.tsx
  components/ui/Pagination.tsx
  components/ui/test.svg
Labels: feature, component

#35 [Feat/component/pagination/DOIT-51] Dropdown 컴포넌트 추가
  components/ui/DropDown.tsx
Labels: feature, component

#46 [Feat/markup/meeting/list/doit-50] 모임 리스트 마크업
  app/meeting/list/components/ConfirmedStatus.tsx
  app/meeting/list/components/Like.tsx
  app/meeting/list/components/Participant.tsx
  app/meeting/list/components/ProgressBar.tsx
  app/meeting/list/components/Title.tsx
  app/meeting/list/page.tsx
  components/shared/Icons/HeartIcon.tsx
  data/mockMeetings.json
  public/assets/card/example_image.png
  public/assets/card/location-marker.svg
Labels: markup

#47 [Feat/component/button/doit-43] 컬러팔레트 수정, 버튼&GNB 스타일 변경
  components/layout/Gnb.md
  components/layout/Gnb.tsx
  components/ui/Button.tsx
  public/assets/mainLogo/logoYW.svg
  public/assets/profile/userProfileDefault.svg
  tailwind.config.ts
Labels: markup

#44 [Feat/markup/user/form/doit-59] Form 컴포넌트 완성
  components/form/.gitkeep
  components/form/Form.tsx
  lib/formValidation.ts
  package-lock.json
  package.json
  yarn.lock
Labels: component

#45 [Feat/markup/user/signin/DOIT-17] 로그인/회원가입 페이지 마크업 완료
  app/user/login/page.tsx
  app/user/signin/page.tsx
  app/user/signup/.gitkeep
  app/user/signup/page.tsx
  public/assets/logo.svg
  public/assets/user/kakaoLogo.svg
  public/assets/user/unVisibility.svg
  public/assets/user/visibility.svg
Labels: markup

#49 [Feat/markup/DOIT-2] 브랜치 병합
  app/meeting/list/components/ConfirmedStatus.tsx
  app/meeting/list/components/Like.tsx
  app/meeting/list/components/Participant.tsx
  app/meeting/list/components/ProgressBar.tsx
  app/meeting/list/components/Title.tsx
  app/meeting/list/page.tsx
  app/user/login/page.tsx
  app/user/signin/page.tsx
  app/user/signup/.gitkeep
  app/user/signup/page.tsx
  components/form/.gitkeep
  components/form/Form.tsx
  components/layout/Gnb.md
  components/layout/Gnb.tsx
  components/shared/Icons/HeartIcon.tsx
  components/ui/Button.tsx
  data/mockMeetings.json
  lib/formValidation.ts
  package-lock.json
  package.json
  public/assets/card/example_image.png
  public/assets/card/location-marker.svg
  public/assets/logo.svg
  public/assets/mainLogo/logoYW.svg
  public/assets/profile/userProfileDefault.svg
  public/assets/user/kakaoLogo.svg
  public/assets/user/unVisibility.svg
  public/assets/user/visibility.svg
  tailwind.config.ts
Labels: merge

#50 [Fix/mvp/meeting/list/lookup/doit-53] 드롭다운 오류 해결
  app/meeting/list/page.tsx
  public/assets/chevron_down.svg
Labels: bug

#56 [feat/mvp/meeting/list/DOIT-52] 중간 브랜치 병합
  app/meeting/list/components/ConfirmedStatus.tsx
  app/meeting/list/components/ProgressBar.tsx
  app/meeting/list/components/Title.tsx
  app/meeting/list/page.tsx
  components/shared/Icons/CheckIcon.tsx
  components/ui/DropDown.tsx
  components/ui/card/MeetingProgress.tsx
  components/ui/modal/datePicker/CustomInput.tsx
  components/ui/modal/datePicker/CustomTimeInput.tsx
  components/ui/modal/datePicker/index.tsx
  components/ui/modal/variants/CreateMeetingModal.tsx
  data/mockMeetings.json
  package-lock 2.json
  package-lock.json
  package.json
  public/assets/chevron_down.svg
  styles/global.css
Labels: merge

#57 [Feat/mvp/detail/lookup/DOIT-57] 상세 내용 구현 완료
  api/meeting/fetchEventById.ts
  app/layout.tsx
  app/meeting/components/ConfirmedStatus.tsx
  app/meeting/components/Participant.tsx
  app/meeting/components/ProgressBar.tsx
  app/meeting/detail/[id]/@description/page.tsx
  app/meeting/detail/[id]/@reviews/page.tsx
  app/meeting/detail/[id]/layout.tsx
  app/meeting/detail/[id]/page.tsx
  app/meeting/detail/components/Avatar/InvisibleAvatar.tsx
  app/meeting/detail/components/Avatar/VisibleAvatar.tsx
  app/meeting/detail/components/AvatarGroup.tsx
  app/meeting/detail/components/EventDetailClient.tsx
  app/meeting/detail/components/EventInfo.tsx
  app/meeting/list/components/Card.tsx
  app/meeting/list/components/Title.tsx
  app/meeting/list/page.tsx
  app/my/components/PropfileCard.tsx
  app/my/page.tsx
  app/mypage/page.tsx
  components/layout/Gnb.tsx
  components/layout/RootLayout.tsx
  components/shared/BaseProfile.tsx
  components/shared/FallbackImage.tsx
  components/shared/Icons/CheckIcon.tsx
  components/ui/DropDown.tsx
  components/ui/Tag.tsx
  components/ui/card/MeetingProgress.tsx
  components/ui/modal/datePicker/CustomInput.tsx
  components/ui/modal/datePicker/CustomTimeInput.tsx
  components/ui/modal/datePicker/index.tsx
  components/ui/modal/variants/CreateMeetingModal.tsx
  data/mockMeetings.json
  package-lock 2.json
  package-lock.json
  package.json
  public/assets/chevron_down.svg
  styles/global.css
  styles/theme.ts
Labels: feature, markup

#61 [Feat/mvp/detail/DOIT-55] 기능 추가 완료오 인한 브랜치 병합
  api/meeting/fetchEventById.ts
  app/layout.tsx
  app/meeting/components/ConfirmedStatus.tsx
  app/meeting/components/Participant.tsx
  app/meeting/components/ProgressBar.tsx
  app/meeting/detail/[id]/@description/page.tsx
  app/meeting/detail/[id]/@reviews/page.tsx
  app/meeting/detail/[id]/layout.tsx
  app/meeting/detail/[id]/page.tsx
  app/meeting/detail/components/Avatar/InvisibleAvatar.tsx
  app/meeting/detail/components/Avatar/VisibleAvatar.tsx
  app/meeting/detail/components/AvatarGroup.tsx
  app/meeting/detail/components/EventDetailClient.tsx
  app/meeting/detail/components/EventInfo.tsx
  app/meeting/list/components/Card.tsx
  app/meeting/list/page.tsx
  app/my/components/PropfileCard.tsx
  app/my/page.tsx
  components/layout/Gnb.tsx
  components/layout/RootLayout.tsx
  components/shared/BaseProfile.tsx
  components/shared/FallbackImage.tsx
  components/shared/Icons/CheckIcon.tsx
  components/ui/Tag.tsx
  package-lock.json
  package.json
  styles/global.css
  styles/theme.ts
Labels: merge

#62 [Feat/mvp/DOIT-3] 상세페이지 구현 완료로 인한 중간 졍핮
  api/meeting/fetchEventById.ts
  app/layout.tsx
  app/meeting/components/ConfirmedStatus.tsx
  app/meeting/components/Participant.tsx
  app/meeting/components/ProgressBar.tsx
  app/meeting/detail/[id]/@description/page.tsx
  app/meeting/detail/[id]/@reviews/page.tsx
  app/meeting/detail/[id]/layout.tsx
  app/meeting/detail/[id]/page.tsx
  app/meeting/detail/components/Avatar/InvisibleAvatar.tsx
  app/meeting/detail/components/Avatar/VisibleAvatar.tsx
  app/meeting/detail/components/AvatarGroup.tsx
  app/meeting/detail/components/EventDetailClient.tsx
  app/meeting/detail/components/EventInfo.tsx
  app/meeting/list/components/Card.tsx
  app/meeting/list/components/Title.tsx
  app/meeting/list/page.tsx
  app/my/components/PropfileCard.tsx
  app/my/page.tsx
  components/layout/Gnb.tsx
  components/layout/RootLayout.tsx
  components/shared/BaseProfile.tsx
  components/shared/FallbackImage.tsx
  components/shared/Icons/CheckIcon.tsx
  components/ui/DropDown.tsx
  components/ui/Tag.tsx
  components/ui/card/MeetingProgress.tsx
  components/ui/modal/datePicker/CustomInput.tsx
  components/ui/modal/datePicker/CustomTimeInput.tsx
  components/ui/modal/datePicker/index.tsx
  components/ui/modal/variants/CreateMeetingModal.tsx
  data/mockMeetings.json
  package-lock.json
  package.json
  public/assets/chevron_down.svg
  styles/global.css
  styles/theme.ts
Labels: merge

#63 [Feat/mvp/detail/review/DOIT58] msw 셋팅 공유를 위한 중간 병합
  api/api.ts
  api/data/mockMeetingDetail.ts
  api/data/mockMeetings.json
  api/meeting/fetchEventById.ts
  api/meeting/fetchMeetingById.ts
  api/meeting/fetchParticipants.ts
  api/mocks/browser.ts
  api/mocks/handler.ts
  api/mocks/handlers.ts
  api/mocks/index.ts
  api/mocks/server.ts
  app/meeting/detail/[id]/@description/page.tsx
  app/meeting/detail/[id]/@reviews/page.tsx
  app/meeting/detail/[id]/layout.tsx
  app/meeting/detail/[id]/page.tsx
  app/meeting/detail/components/EventInfo.tsx
  app/meeting/detail/components/MeetingDetailClient.tsx
  app/meeting/detail/components/ReviewList.tsx
  app/meeting/list/page.tsx
  components/layout/RootLayout.tsx
  components/shared/BaseProfile.tsx
  components/ui/chip/ChipInfo.tsx
  components/ui/review/ReviewHeart.tsx
  components/ui/review/ReviewItem.tsx
  data/.gitkeep
  data/mockEventDetail.ts
  hooks/useMeeting.ts
  hooks/useMeetingDetail.ts
  package-lock.json
  package.json
  public/mockServiceWorker.js
  types/.gitkeep
  types/meeting.ts
  utils/formatDateTime.ts
Labels: merge

#64 [Feat/mvp/detail/DOIT-55] msw틀 공유를 위한 중간 병합
  api/api.ts
  api/data/mockMeetingDetail.ts
  api/data/mockMeetings.json
  api/meeting/fetchEventById.ts
  api/meeting/fetchMeetingById.ts
  api/meeting/fetchParticipants.ts
  api/mocks/browser.ts
  api/mocks/handler.ts
  api/mocks/handlers.ts
  api/mocks/index.ts
  api/mocks/server.ts
  app/meeting/detail/[id]/@description/page.tsx
  app/meeting/detail/[id]/@reviews/page.tsx
  app/meeting/detail/[id]/layout.tsx
  app/meeting/detail/[id]/page.tsx
  app/meeting/detail/components/EventInfo.tsx
  app/meeting/detail/components/MeetingDetailClient.tsx
  app/meeting/detail/components/ReviewList.tsx
  app/meeting/list/page.tsx
  components/layout/RootLayout.tsx
  components/shared/BaseProfile.tsx
  components/ui/chip/ChipInfo.tsx
  components/ui/review/ReviewHeart.tsx
  components/ui/review/ReviewItem.tsx
  data/.gitkeep
  data/mockEventDetail.ts
  hooks/useMeeting.ts
  hooks/useMeetingDetail.ts
  package-lock.json
  package.json
  public/mockServiceWorker.js
  types/.gitkeep
  types/meeting.ts
  utils/formatDateTime.ts
Labels: merge

#60 [Feat/mvp/list/create/DOIT-54] meetingSummary 및 스크롤 기능 추가
  components/ui/modal/Modal.tsx
  components/ui/modal/variants/CreateMeetingModal.tsx
Labels: feature

#65 [Feat/mvp/detail/review/DOIT-58] 상세페이지 msw, 리액트 쿼리 적용
  api/api.ts
  api/data/mockMeetingDetail.ts
  api/data/mockMeetings.json
  api/meeting/fetchEventById.ts
  api/meeting/fetchMeetingById.ts
  api/meeting/fetchParticipants.ts
  api/mocks/browser.ts
  api/mocks/handler.ts
  api/mocks/handlers.ts
  api/mocks/index.ts
  api/mocks/server.ts
  app/meeting/detail/[id]/@description/page.tsx
  app/meeting/detail/[id]/@reviews/page.tsx
  app/meeting/detail/[id]/layout.tsx
  app/meeting/detail/[id]/page.tsx
  app/meeting/detail/components/EventInfo.tsx
  app/meeting/detail/components/MeetingDetailClient.tsx
  app/meeting/detail/components/ReviewList.tsx
  app/meeting/list/page.tsx
  app/page.tsx
  components/layout/RootLayout.tsx
  components/shared/BaseProfile.tsx
  components/ui/card/MeetingProgress.tsx
  components/ui/chip/ChipInfo.tsx
  components/ui/modal/Modal.tsx
  components/ui/modal/variants/CreateMeetingModal.tsx
  components/ui/review/ReviewHeart.tsx
  components/ui/review/ReviewItem.tsx
  data/.gitkeep
  data/mockEventDetail.ts
  hooks/useMeeting.ts
  hooks/useMeetingDetail.ts
  package-lock.json
  package.json
  public/mockServiceWorker.js
  types/.gitkeep
  types/meeting.ts
  utils/formatDateTime.ts
Labels: merge

#70 [Feat/mvp/meeting/list/DOIT-52] 배포 확인용 중간 배포
  api/data/mockMeetings.json
  api/data/mockMeetings.ts
  api/meeting/fetchMeeting.ts
  api/meeting/toggleLike.ts
  api/mocks/handlers.ts
  app/meeting/list/components/Like.tsx
  app/meeting/list/components/MeetingInfo.tsx
  app/meeting/list/components/MeetingList.tsx
  app/meeting/list/page.tsx
  app/meeting/list/regions.ts
  components/ui/DropDown.tsx
  components/ui/EmptyMessage.tsx
  components/ui/chip/Chip.tsx
  components/ui/chip/ChipInfo.tsx
  types/meeting.types.d.ts
Labels: merge

#71 [Feat/api/user] 회원가입/로그인 API 연결
  api/api.ts
  api/auth.ts
  app/layout.tsx
  app/user/signin/page.tsx
  app/user/signup/page.tsx
  components/form/Form.tsx
  components/layout/RootLayout.tsx
  lib/formValidation.ts
  package-lock.json
  package.json
  public/assets/logo.svg
  types/auth.types.d.ts
Labels: API

#72 [Feat/component/gnb/DOIT-48] 로그인 상태에 따른 GNB NavItem 처리
  app/layout.tsx
  components/layout/Gnb.tsx
Labels: component

#73 Feat/mvp/detail/DOIT-55
  api/data/mockMeetingDetail.ts
  api/data/mockMeetings.ts
  api/meeting/fetchMeetingById.ts
  api/mocks/setup.ts
  app/layout.tsx
  app/meeting/detail/[id]/@description/page.tsx
  app/meeting/detail/[id]/@reviews/page.tsx
  app/meeting/detail/[id]/layout.tsx
  app/meeting/detail/[id]/page.tsx
  app/meeting/detail/components/MeetingDetailClient.tsx
  app/meeting/detail/components/skeleton/DescriptionSkeleton.tsx
  app/meeting/detail/components/skeleton/MeetingDetailSkeleton.tsx
  app/meeting/detail/components/skeleton/ReviewSkeleton.tsx
  app/meeting/list/components/Like.tsx
  app/myprofile/layout 2.tsx
  components/layout/Gnb.tsx
  components/layout/RootLayout.tsx
  components/shared/FallbackImage.tsx
  components/ui/EmptyMessage 2.tsx
  components/ui/card/MeetingProgress.tsx
  package-lock.json
  package.json
  types/meeting.ts
  types/meeting.types.d.ts
Labels: merge

#81 [!HOTFIX: deploy 오류 해결]
  api/data/mockMeetings.ts
  api/meeting/fetchMeeting.ts
  api/meeting/toggleLike.ts
  api/mocks/handlers.ts
  app/meeting/list/components/Like.tsx
  app/meeting/list/components/MeetingInfo.tsx
  app/meeting/list/components/MeetingList.tsx
  app/meeting/list/page.tsx
  components/ui/card/MeetingProgress.tsx
  components/ui/chip/Category.tsx
  hooks/useMeeting.ts
  types/meeting.types.d.ts
Labels: bug

#83 [feat/component/user] user페이지 CSS 수정 & Auth.ts 수정
  api/auth.ts
  app/user/signin/page.tsx
  app/user/signup/page.tsx
  components/form/Form.tsx
Labels: markup

#84 [Feat/setting/PWASetting/DOIT-73] PWA 셋팅이 추가
  app/layout.tsx
  components/layout/RootLayout.tsx
  next.config.js
  next.config.ts
  package-lock.json
  package.json
  public/icons/icon-192x192.png
  public/icons/icon-512x512.png
  public/manifest.json
  public/sw.js
  public/workbox-4754cb34.js
Labels: setting

#86 [Feat/api/meeting/list/create/DOIT-72] 폼 제출 핸들러 및 Kakao 로컬 api 사용, 키워드로 장소 검색 기능 추가
  api/README.md
  api/api.ts
  api/auth.ts
  api/data/mockMeetingDetail.ts
  api/data/mockMeetings.ts
  api/data/mockMyPageMeetings.ts
  api/data/mockMyPageReviews.ts
  api/meeting/createMeeting.ts
  api/meeting/fetchMeeting.ts
  api/meeting/fetchMeetingById.ts
  api/meeting/toggleLike.ts
  api/meeting/updateMeetingDescription.ts
  api/mocks/handlers.ts
  api/mocks/setup.ts
  api/myPage/myPage.ts
  app/layout.tsx
  app/meeting/detail/[id]/@description/page.tsx
  app/meeting/detail/[id]/@reviews/page.tsx
  app/meeting/detail/[id]/layout.tsx
  app/meeting/detail/[id]/page.tsx
  app/meeting/detail/components/MeetingDetailClient.tsx
  app/meeting/detail/components/skeleton/DescriptionSkeleton.tsx
  app/meeting/detail/components/skeleton/MeetingDetailSkeleton.tsx
  app/meeting/detail/components/skeleton/ReviewSkeleton.tsx
  app/meeting/list/components/Like.tsx
  app/meeting/list/components/MeetingInfo.tsx
  app/meeting/list/components/MeetingList.tsx
  app/meeting/list/page.tsx
  app/myprofile/@meeting/page.tsx
  app/user/signin/page.tsx
  app/user/signup/page.tsx
  components/form/Form.tsx
  components/layout/Gnb.tsx
  components/layout/RootLayout.tsx
  components/shared/BaseProfile.tsx
  components/shared/FallbackImage.tsx
  components/ui/EmptyMessage 2.tsx
  components/ui/Pagination.tsx
  components/ui/card/MeetingProgress.tsx
  components/ui/chip/Category.tsx
  components/ui/modal/SearchPlace.tsx
  components/ui/modal/variants/CreateMeetingModal.tsx
  hooks/README.md
  hooks/useMeeting.ts
  lib/auth.ts
  lib/formValidation.ts
  next.config.js
  next.config.ts
  package-lock.json
  package.json
  public/assets/chat.svg
  public/assets/logo.svg
  public/icons/icon-192x192.png
  public/icons/icon-512x512.png
  public/manifest.json
  public/sw.js
  public/workbox-4754cb34.js
  types/auth.types.d.ts
  types/meeting.ts
  types/meeting.types.d.ts
Labels: API

#87 [Feat/api/user/signin/DOIT-65] user 페이지 mutation적용 & CSS수정
  api/auth.ts
  app/user/signin/page.tsx
  app/user/signup/page.tsx
  components/layout/Gnb.tsx
  components/layout/RootLayout.tsx
  hooks/useAuth.ts
  package-lock.json
  package.json
Labels: API

#90 DOIT-77 deploy: 배포 시 msw 서비스 워커 실행
  components/layout/RootLayout.tsx
  components/shared/query/ErrorBoundary.tsx
Labels: API

#92 [Feat/api/meeting/list/lookup/doit-71] framer motion 적용
  api/auth.ts
  api/data/mockMeetings.ts
  app/layout.tsx
  app/meeting/components/HostInfo.tsx
  app/meeting/components/ProgressBar.tsx
  app/meeting/list/components/MeetingInfo.tsx
  app/meeting/list/components/MeetingItem.tsx
  app/meeting/list/components/MeetingList.tsx
  app/meeting/list/components/skeleton/MeetingCardSkeleton.tsx
  app/meeting/list/regions.ts
  app/user/signin/page.tsx
  app/user/signup/page.tsx
  components/layout/Gnb.tsx
  components/layout/RootLayout.tsx
  components/shared/query/ErrorBoundary.tsx
  components/ui/DropDown.tsx
  components/ui/EmptyMessage 2.tsx
  components/ui/chip/Chip.tsx
  hooks/useAuth.ts
  hooks/useMeeting.ts
  lib/constants/filters.ts
  lib/constants/index.ts
  lib/constants/meeting.ts
  next.config.js
  next.config.ts
  package-lock.json
  package.json
  public/assets/profile/userProfileDarkDefault.svg
  public/icons/icon-192x192.png
  public/icons/icon-512x512.png
  public/manifest.json
  public/sw.js
  public/workbox-4754cb34.js
  styles/global.css
  types/meeting.types.d.ts
  types/regions.ts
  utils/formatDateTime.ts
Labels: feature
