Repository DoITFronts/Frontend, pull requests merged in 2025-03, with the labels that each got.

#107 [Feat/api/liked/DOIT-78] 좋아요 기능 & 랜딩페이지
  api/api.ts
  api/meeting/toggleLike.ts
  app/liked/page.tsx
  app/meeting/list/components/MeetingInfo.tsx
  app/page.tsx
  components/layout/RootLayout.tsx
  hooks/useLikeToggle.ts
  package-lock.json
  package.json
  public/assets/landing/fireworks.json
  public/assets/landing/section01.svg
  public/assets/landing/section02.svg
  public/assets/logoWhite.svg
Labels: markup, API

#108 [Feat/api/meeting/list/create/DOIT-72] feat: 버튼박스 컴포넌트 완성
  api/data/mockMeetings.ts
  api/meeting/createMeeting.ts
  api/meeting/fetchMeetingById.ts
  app/meeting/components/ProgressBar.tsx
  app/meeting/list/components/MeetingInfo.tsx
  app/meeting/list/components/MeetingItem.tsx
  app/meeting/list/components/MeetingList.tsx
  app/meeting/list/regions.ts
  app/myprofile/@meeting/page.tsx
  components/ui/ButtonBox.tsx
  components/ui/DropDown.tsx
  components/ui/chip/Chip.tsx
  components/ui/modal/SearchPlace.tsx
  components/ui/modal/variants/CreateMeetingModal.tsx
  lib/constants/filters.ts
  lib/constants/index.ts
  lib/constants/meeting.ts
  package-lock.json
  package.json
  styles/global.css
  types/meeting.ts
  types/meeting.types.d.ts
  utils/formatDateTime.ts
Labels: feature, component

#110 [Feat/api/meeting/list/lookup/doit-71] 모임 목록 조회 API 연결
  api/data/mockMeetings.ts
  api/data/mockMyPageMeetings.md
  api/data/mockMyPageReviews.md
  api/meeting/fetchMeeting.ts
  api/mocks/handlers.ts
  app/meeting/components/HostInfo.tsx
  app/meeting/list/components/Like.tsx
  app/meeting/list/components/MeetingInfo.tsx
  app/meeting/list/components/MeetingList.tsx
  app/meeting/list/page.tsx
  app/myprofile/@meeting/page.tsx
  components/ui/card/MeetingProgress.tsx
  hooks/useMeeting.ts
  next.config.ts
  package-lock.json
  styles/global.css
  types/categoryMap.ts
  types/cityMap.ts
  types/meeting.types.d.ts
Labels: API

#111 [!HOTFIX/api/meeting/detail/DOIT-79] 버그 수정
  api/data/mockMeetings.ts
  app/meeting/list/components/Like.tsx
  app/meeting/list/components/MeetingInfo.tsx
  app/meeting/list/components/MeetingList.tsx
  app/myprofile/@meeting/page.tsx
  components/ui/Button.tsx
  components/ui/ButtonBox.tsx
  components/ui/card/MeetingProgress.tsx
  types/meeting.types.d.ts
Labels: bug

#112 [Feat/api/meeting/detail/DOIT-79] api 연동으로 인한 msw 제거
  api/data/mockMeetingDetail.md
  api/data/mockMyPageMeetings.ts
  api/data/mockMyPageReviews.ts
  api/meeting/fetchMeeting.ts
  api/meeting/fetchMeetingById.ts
  api/mocks/handlers.ts
  app/meeting/list/regions.ts
  components/layout/RootLayout.tsx
  next.config.ts
  package-lock.json
  package.json
  types/meeting.ts
Labels: API

#113 [Feat/api/type setting/DOIT-90] 안전성과 유지보수성을 고려한 타입 셋팅
  package-lock.json
  package.json
  types/meeting.ts
  types/meeting.types.d.ts
  types/regions.ts
  types/review.ts
Labels: API

#116 [Feat/api/meeting/list/DOIT-70] 브랜치 병합
  api/meeting/fetchMeeting.ts
  app/meeting/list/components/MeetingList.tsx
  app/meeting/list/regions 2.ts
  hooks/useMeeting.ts
  lib/constants/filters.ts
Labels: merge

#119 [Feat/api/meeting/detail/DOIT-79] api 연결 완료
  api/meeting/fetchMeetingById.ts
  app/meeting/detail/[id]/@bottombar/page.tsx
  app/meeting/detail/[id]/@card/page.tsx
  app/meeting/detail/[id]/@description/page.tsx
  app/meeting/detail/[id]/@location/page.tsx
  app/meeting/detail/[id]/@reviews/page.tsx
  app/meeting/detail/components/skeleton/BottomFloatingBarSkeleton.tsx
  app/meeting/detail/components/skeleton/DescriptionSkeleton.tsx
  app/meeting/detail/components/skeleton/DetailCardSkeleton.tsx
  app/meeting/detail/components/skeleton/HostInfoSkeleton.tsx
  app/meeting/detail/components/skeleton/LocationSkeleton.tsx
  app/meeting/detail/components/skeleton/ReviewSkeleton.tsx
Labels: API

#118 [Feat/api/user/signin/DOIT-65] Refactor: 유저페이지, 자잘한 이슈들
  api/api.ts
  app/meeting/list/components/MeetingInfo.tsx
  app/page.tsx
  app/user/signin/page.tsx
  app/user/signup/page.tsx
  components/form/Form.tsx
  hooks/useAuth.ts
  lib/formValidation.ts
Labels: feature

#120 [Feat/api/DOIT-4] 브랜치 병합
  api/meeting/fetchMeetingById.ts
  app/meeting/detail/[id]/@bottombar/page.tsx
  app/meeting/detail/[id]/@card/page.tsx
  app/meeting/detail/[id]/@description/page.tsx
  app/meeting/detail/[id]/@location/page.tsx
  app/meeting/detail/[id]/@reviews/page.tsx
  app/meeting/detail/components/skeleton/BottomFloatingBarSkeleton.tsx
  app/meeting/detail/components/skeleton/DescriptionSkeleton.tsx
  app/meeting/detail/components/skeleton/DetailCardSkeleton.tsx
  app/meeting/detail/components/skeleton/HostInfoSkeleton.tsx
  app/meeting/detail/components/skeleton/LocationSkeleton.tsx
  app/meeting/detail/components/skeleton/ReviewSkeleton.tsx
Labels: merge

#121 !HOTFIX: null 방지 처리
  hooks/useMeeting.ts
Labels: bug

#122 [Feat/advanced/meeting/detail/DOIT-95] 카카오 지도 수정, 프로필 이미지 홀짝 반영, 태그 수정, 스플래쉬 추가, favicon추가
  .github/workflow/lint.yml
  app/favicon.ico
  app/meeting/detail/[id]/@card/page.tsx
  app/meeting/detail/[id]/@host/page.tsx
  app/meeting/detail/[id]/@location/page.tsx
  app/meeting/detail/components/AvatarGroup.tsx
  app/meeting/detail/components/info/MeetingDetailFooter.tsx
  app/meeting/detail/components/info/MeetingDetailHeader.tsx
  app/myprofile/@profile/page.tsx
  app/page.tsx
  components/layout/Gnb.tsx
  components/layout/RootLayout.tsx
  components/layout/SplashScreen.tsx
  components/shared/BaseProfile.tsx
  components/ui/Tag.tsx
  components/ui/review/ReviewItem.tsx
  hooks/useAuth.ts
  hooks/useKakaoPlaceInfo.ts
  hooks/useUserInfo.ts
  package-lock.json
  package.json
  public/assets/mainLogo/splash.svg
  store/themeStore.ts
  store/userStore.ts
  types/meeting.ts
Labels: optimize

#135 [Feat/api/mypage/DOIT-86] 🚨 hotFix: 모임 만들기 에러 해결, buttonBox컴포넌트 추가
  .github/pull_request_template.md
  .github/workflow/cr.yml
  .github/workflow/lint.yml
  .husky/pre-commit
  api/api.ts
  api/data/mockMyProfile.ts
  api/meeting/createMeeting.ts
  api/myPage/myPage.ts
  app/meeting/list/components/MeetingInfo.tsx
  app/myprofile/@meeting/page.tsx
  app/myprofile/@profile/page.tsx
  app/page.tsx
  app/user/signin/page.tsx
  app/user/signup/page.tsx
  components/form/Form.tsx
  components/ui/ButtonBox.tsx
  components/ui/modal/variants/CreateMeetingModal.tsx
  hooks/useAuth.ts
  hooks/useMeeting.ts
  lib/formValidation.ts
  store/useProfileStore.ts
  types/auth.types.d.ts
  types/createMeeting.ts
  types/meeting.ts
Labels: bug, component

#136 [Feat/api/DOIT-4] 버그 해결
  api/data/mockMyProfile.ts
  api/meeting/createMeeting.ts
  api/myPage/myPage.ts
  app/meeting/list/components/MeetingInfo.tsx
  app/myprofile/@meeting/page.tsx
  app/myprofile/@profile/page.tsx
  components/ui/ButtonBox.tsx
  components/ui/modal/variants/CreateMeetingModal.tsx
  store/useProfileStore.ts
  types/auth.types.d.ts
  types/createMeeting.ts
  types/meeting.ts
Labels: bug

#137 [Feat/mvp/DOIT-3] 브랜치 병합
  api/meeting/fetchReviews.ts
  app/review/components/ReviewItem.tsx
  app/review/components/ReviewList.tsx
  app/review/components/ReviewStatus.tsx
  app/review/components/skeleton/ReviewSkeleton.tsx
  app/review/page.tsx
  hooks/useReview.ts
Labels: merge

#139 [Feat/advanced/meeting/list/lookup/doit-97] 모임 목록 개선사항 추가
  api/meeting/fetchMeeting.ts
  api/meeting/fetchReviews.ts
  app/meeting/components/ConfirmedStatus.tsx
  app/meeting/list/.gitkeep
  app/meeting/list/components/Card.tsx
  app/meeting/list/components/DateDisplay.tsx
  app/meeting/list/components/Join.tsx
  app/meeting/list/components/Like.tsx
  app/meeting/list/components/MeetingInfo.tsx
  app/meeting/list/components/MeetingItem.tsx
  app/meeting/list/components/MeetingList.tsx
  app/meeting/list/components/TimeDisplay.tsx
  app/meeting/list/page.tsx
  components/ui/DropDown.tsx
  components/ui/card/FilterDropdown.tsx
  hooks/useLikeMutation.ts
  hooks/useMeeting.ts
  next.config.ts
  public/assets/exit.svg
  public/assets/sort.svg
  types/cityMap.ts
  types/orderMap.ts
Labels: bug, API, optimize

#140 [feat/api/mypage/DOIT-86] 마이프로필 페이지 api연동, 프로필 수정 기능 추가
  api/meeting/createMeeting.ts
  api/myPage/myPage.ts
  app/myprofile/@meeting/page.tsx
  app/myprofile/@profile/page.tsx
  components/ui/modal/SearchPlace.tsx
  components/ui/modal/variants/CreateMeetingModal.tsx
  components/ui/modal/variants/ProfileModal.tsx
  public/userProfile.svg
  store/useProfileStore.ts
  types/auth.types.d.ts
  types/createMeeting.ts
  types/meeting.ts
Labels: API

#141 !HOTFIX: onJoin 삭제
  app/meeting/list/components/MeetingItem.tsx
Labels: bug

#142 [Feat/mvp/reviews/doit-92] 모든 리뷰 페이지 기능 추가, API 연결
  api/review/fetchReview.ts
  app/review/components/ReviewItem.tsx
  app/review/components/ReviewList.tsx
  app/review/components/ReviewStatus.tsx
  app/review/page.tsx
  components/shared/Icons/HeartIcon.tsx
  hooks/useReview.ts
  types/orderMap.ts
  types/review.ts
Labels: feature, API

#144 [Feat/advanced/reviews/doit-100] 모든 리뷰 목록 개선사항 추가
  api/review/fetchReview.ts
  app/meeting/list/components/MeetingList.tsx
  app/not-found.tsx
  app/review/components/ReviewItem.tsx
  app/review/components/ReviewList.tsx
  app/review/components/ReviewStatus.tsx
  components/ui/review/ReviewHeart.tsx
  components/ui/review/ReviewItem.tsx
Labels: feature, optimize, Refactor

#146 [Feat/advanced/meeting/detail/DOIT-95]
  api/chat/chatApi.ts
  api/meeting/fetchReviews.ts
  api/meeting/updateMeetingDescription.ts
  api/review/createReview.ts
  api/review/fetchDetailReview.ts
  app/meeting/detail/[id]/@description/page.tsx
  app/meeting/detail/[id]/@host/page.tsx
  app/meeting/detail/[id]/@location/page.tsx
  app/meeting/detail/[id]/@reviews/page.tsx
  app/meeting/list/.gitkeep
  app/meeting/list/components/MeetingItem.tsx
  app/meeting/list/regions 2.ts
  components/ui/modal/Modal.tsx
  components/ui/modal/variants/CreateReviewModal.tsx
  components/ui/review/ReviewHeartSelectable.tsx
  hooks/useChat.ts
  hooks/useKakaoMap.ts
  hooks/useKakaoPlaceInfo.ts
  hooks/useMeetingDetail.ts
  hooks/useWebSocket.ts
  next.config.ts
  package-lock.json
  package.json
  store/chatStore.ts
  store/useModalStore.ts
  store/userStore.ts
  types/cityMap.ts
  types/meeting.ts
  types/review.ts
Labels: API, optimize

#147 [hotfix] type 수정 및 오탈자 수정
  app/liked/page.tsx
  app/meeting/list/components/MeetingList.tsx
  app/review/components/ReviewList.tsx
Labels: API, optimize

#149 [Feat/api/mypage/DOIT-86] myPage Suspense패턴 구현 및 구조 개선, 스켈레톤 적용
  api/myPage/myPage.ts
  app/myprofile/@meeting/page.tsx
  app/myprofile/components/GridSkeleton.tsx
  app/myprofile/components/MeetingCardSkeleton.tsx
  app/myprofile/components/MeetingTab.tsx
  app/myprofile/layout.tsx
  components/layout/RootLayout.tsx
  components/ui/ButtonBox.tsx
  hooks/useKakaoMap.ts
  hooks/useKakaoPlaceInfo.ts
  hooks/useMeetingToggle.ts
Labels: feature, API, Refactor

#148 [Feat/mvp/liked/DOIT-69] GNB 프로필정보 연동 & 좋아요,인풋 작은 이슈들 해결
  app/liked/page.tsx
  app/meeting/list/components/Like.tsx
  app/meeting/list/components/MeetingList.tsx
  components/form/Form.tsx
  components/layout/Gnb.tsx
Labels: Refactor

#160 [Feat/optimize/meeting/list/lookup/doit-102] 중간 build 에러 해결
  api/meeting/fetchMeeting.ts
  api/myPage/myPage.ts
  app/liked/page.tsx
  app/meeting/detail/[id]/@bottombar/page.tsx
  app/meeting/detail/[id]/@card/page.tsx
  app/meeting/detail/[id]/@host/page.tsx
  app/meeting/detail/[id]/@reviews/page.tsx
  app/meeting/detail/components/AvatarGroup.tsx
  app/meeting/detail/components/info/MeetingDetailFooter.tsx
  app/meeting/detail/components/info/MeetingDetailHeader.tsx
  app/meeting/list/@title/page.tsx
  app/meeting/list/components/MeetingList.tsx
  app/myprofile/@meeting/page.tsx
  app/myprofile/@profile/page.tsx
  app/myprofile/components/MeetingTab.tsx
  app/not-found.tsx
  app/page.tsx
  app/review/components/ReviewItem.tsx
  app/review/components/ReviewList.tsx
  app/review/components/ReviewStatus.tsx
  app/user/component/Form.tsx
  app/user/signin/page.tsx
  components/layout/Gnb.tsx
  components/ui/card/Card.tsx
  components/ui/card/CardItem.tsx
  components/ui/card/component/Like.tsx
  components/ui/card/component/MeetingStatus.tsx
  components/ui/dropdown/FilterDropdown.tsx
  components/ui/modal/datePicker/CustomInput.tsx
  components/ui/modal/datePicker/index.tsx
  components/ui/modal/variants/CreateMeetingModal.tsx
  components/ui/modal/variants/CreateReviewModal.tsx
  components/ui/modal/variants/DeleteMeetingModal.tsx
  components/ui/modal/variants/ProfileModal.tsx
Labels: bug

#168 [Feat/optimize/meeting/list/lookup/doit-102] 모임 목록 페이지, 모든 리뷰 페이지 반응형 UI 적용
  app/meeting/list/@title/page.tsx
  app/meeting/list/components/MeetingList.tsx
  app/meeting/list/layout.tsx
  app/review/@reviewList/page.tsx
  app/review/@title/page.tsx
  app/review/components/ReviewItem.tsx
  app/review/components/ReviewList.tsx
  app/review/components/ReviewStatus.tsx
  app/review/layout.tsx
  components/layout/RootLayout.tsx
  components/layout/SplashScreen.tsx
  components/ui/button/ButtonBox.tsx
  components/ui/card/CardItem.tsx
  components/ui/card/component/ConfirmedStatus.tsx
  components/ui/card/component/MeetingStatus.tsx
  components/ui/card/component/Participant.tsx
  components/ui/card/component/Title.tsx
  components/ui/chip/CategoryFilter.tsx
  components/ui/chip/ChipDate.tsx
  components/ui/dropdown/DropDown.tsx
  components/ui/dropdown/FilterDropdown.tsx
  components/ui/modal/datePicker/CustomInput.tsx
  components/ui/review/ReviewItem.tsx
  types/meeting.ts
  types/review.ts
  utils/formatDateTime.ts
Labels: optimize

#169 [Feat/optimize/meeting/detail/DOIT-104] 미디어 쿼리 적용, 지도에 줌 기능 추가
  app/meeting/detail/[id]/@bottombar/page.tsx
  app/meeting/detail/[id]/@card/page.tsx
  app/meeting/detail/[id]/@description/page.tsx
  app/meeting/detail/[id]/@location/page.tsx
  app/meeting/detail/[id]/layout.tsx
  app/meeting/detail/components/AvatarGroup.tsx
  app/meeting/detail/components/info/MeetingDetailFooter.tsx
  app/meeting/detail/components/info/MeetingDetailHeader.tsx
  components/layout/SplashScreen.tsx
  components/ui/modal/variants/SignUpModal.tsx
  cypress/fixtures/example 2.json
  cypress/support/commands 2.ts
  cypress/support/e2e 2.ts
  hooks/README.md
  hooks/useKakaoMap.ts
  package-lock.json
  package.json
  public/assets/logo/cursor.png
  styles/global.css
Labels: optimize

#171 [Feat/optimize/meeting/list/lookup/doit-102] fallback 이미지 추가, 로딩 스피너 적용
  app/meeting/detail/[id]/@card/page.tsx
  app/meeting/list/@title/page.tsx
  app/meeting/list/components/MeetingList.tsx
  app/meeting/list/layout.tsx
  components/layout/RootLayout.tsx
  components/shared/FallbackImage.tsx
  components/skeleton/LoadingSpinner.tsx
  components/ui/card/CardItem.tsx
  components/ui/modal/variants/DeleteMeetingModal.tsx
  components/utils/FallbackImage.tsx
  public/assets/fallback/img.png
  public/fallback/fallback_board_game.png
  public/fallback/fallback_cafe.png
  public/fallback/fallback_default.png
  public/fallback/fallback_gourmet.png
Labels: chore

#172 [Feat/setting/DOIT-14] PWA setting 수정
  app/meeting/list/components/DateDisplay.tsx
  app/meeting/list/components/Join.tsx
  app/meeting/list/components/MeetingInfo.tsx
  app/meeting/list/components/TimeDisplay.tsx
  app/page.tsx
  components/ui/PWAInstaller.tsx
  constants/commonText.ts
  constants/errorText.ts
  constants/etcText.ts
  constants/successText.ts
  constants/warningText.ts
  lib/pwa.ts
  next.config.js
  next.config.ts
  package-lock.json
  package.json
  public/manifest.json
Labels: optimize

#173 [Feat/setting/DOIT-14] 컨플릭 해결
  app/page.tsx
  components/ui/button/PWAInstaller.tsx
  constants/warningText.ts
  package-lock.json
  package.json
Labels: optimize

#176 [Cicd/DOIT-108] sentry, codecov 셋팅 circle ci에 추가
  .cirlcleci/config.yml
  .github/workflow/cr.yml
  .gitignore
  api/client/meeting/createMeeting.ts
  api/client/myPage/myPage.ts
  api/server/fetchMeeting.ts
  app/api/sentry-example-api/route.ts
  app/global-error.tsx
  app/liked/page.tsx
  app/meeting/detail/[id]/@card/page.tsx
  app/meeting/detail/[id]/@reviews/page.tsx
  app/meeting/detail/components/AvatarGroup.tsx
  app/meeting/detail/components/info/MeetingDetailFooter.tsx
  app/meeting/list/components/MeetingList.tsx
  app/myprofile/components/MeetingTab.tsx
  app/review/components/ReviewItem.tsx
  app/review/components/ReviewList.tsx
  app/review/components/ReviewStatus.tsx
  app/sentry-example-page/page.tsx
  components/ui/card/CardItem.tsx
  components/ui/modal/variants/CreateMeetingModal.tsx
  hooks/like/useLikeMutation.ts
  hooks/meeting/useMeetingDetail.ts
  hooks/meeting/useMeetingToggle.ts
  instrumentation.ts
  next.config.ts
  package-lock.json
  package.json
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  test/unit/hooks/useMeetingDetail.test.ts
  types/map/categoryMap.ts
  types/map/cityMap.ts
  types/map/orderMap.ts
  types/map/regions.ts
  types/meeting/createMeeting.ts
  types/meeting/description.ts
  types/meeting/meeting.ts
  types/review/review.ts
  types/user/auth.types.d.ts
  utils/queryParams.ts
Labels: CICD

#178 [Cicd/DOIT-108] Google Analytics, lighthouse CI 추가
  app/global-error.tsx
  app/layout.tsx
  app/sentry-example-page/page.tsx
  lighthouserc.json
  utils/gtag.ts
Labels: CICD

#179 [Feat/setting/DOIT-14] 커스텀 커서 추가, 메타 데이터 추가, 토스트 텍스트 수정, 패키지 구조 정리
  api/client/myPage/myPage.ts
  app/layout.tsx
  app/liked/page.tsx
  app/manifest.ts
  app/meeting/detail/[id]/@bottombar/page.tsx
  app/meeting/list/@title/page.tsx
  app/meeting/list/components/MeetingList.tsx
  app/myprofile/@profile/page.tsx
  app/review/components/ReviewList.tsx
  components/layout/Gnb.tsx
  components/layout/RootLayout.tsx
  components/shared/BaseProfile.tsx
  components/ui/button/PWAInstaller.tsx
  components/ui/card/CardItem.tsx
  components/ui/modal/Modal.tsx
  components/ui/modal/datePicker/CustomInput.tsx
  components/ui/modal/variants/CreateMeetingModal.tsx
  components/ui/modal/variants/CreateReviewModal.tsx
  components/ui/modal/variants/DeleteMeetingModal.tsx
  components/ui/modal/variants/ProfileModal.tsx
  components/utils/BaseProfile.tsx
  constants/commonText.ts
  constants/etcText.ts
  constants/successText.ts
  hooks/like/useLikeCount.ts
  hooks/like/useLikeToggle.ts
  lib/constants/meeting/filters.ts
  lib/constants/meeting/index.ts
  lib/constants/meeting/meeting.ts
  lib/constants/toast/index.ts
  lib/constants/toast/text/errorText.ts
  lib/constants/toast/text/successText.ts
  lib/constants/toast/text/warningText.ts
  package-lock.json
  public/assets/calendar.svg
  public/assets/cursor/cursor-click.svg
  public/assets/cursor/cursor-hover.svg
  public/assets/cursor/cursor.svg
  public/assets/file.svg
  public/assets/globe.svg
  public/assets/logo/cursor.png
  public/assets/userProfile.svg
  public/assets/window.svg
  public/manifest.json
  public/mockServiceWorker.js
  public/next.svg
  public/offline.html
  public/sw.js
  public/sw.js.map
  public/vercel.svg
  public/workbox-4754cb34.js
  public/workbox-4754cb34.js.map
  store/likeCountStore.ts
  store/modalStore.ts
  store/profileStore.ts
  styles/global.css
Labels: optimize

#180 [feat/setting/DOIT-14] feat: pwa 안보이는 부분 해결
  app/page.tsx
  components/ui/button/PWAInstaller.tsx
Labels: optimize

#181 [Test/user/signup/DOIT-80] 좋아요 컴포넌트 리팩토링 & Toast 메세지 상수화
  api/middleware/api.ts
  api/socket/websocket.ts
  app/layout.tsx
  app/meeting/detail/[id]/@bottombar/page.tsx
  app/meeting/detail/[id]/@card/page.tsx
  app/meeting/list/components/MeetingList.tsx
  components/ui/card/CardItem.tsx
  components/ui/card/component/Like.tsx
  components/ui/modal/variants/CreateMeetingModal.tsx
  components/ui/modal/variants/CreateReviewModal.tsx
  components/ui/modal/variants/ProfileModal.tsx
  hooks/chat/useWebSocket.ts
  hooks/like/useLikeMutation.ts
  hooks/meeting/useMeetingToggle.ts
  hooks/user/useSignUp.ts
  hooks/user/useSignin.ts
  hooks/user/useSignout.ts
  lib/constants/toast/text/errorText.ts
  lib/constants/toast/text/successText.ts
  styles/global.css
Labels: Refactor

#182 [Feat/api/mypage/DOIT-86 fix2] 마이페이지 수정
  .eslintrc.js
  .prettierrc
  api/client/meeting/createMeeting.ts
  api/client/myPage/myPage.ts
  app/myprofile/@meeting/page.tsx
  app/myprofile/@profile/page.tsx
  app/myprofile/components/GridSkeleton.tsx
  app/myprofile/components/MeetingCardSkeleton.tsx
  app/myprofile/components/MeetingTab.tsx
  app/myprofile/components/ReviewTab.tsx
  app/myprofile/layout.tsx
  components/layout/SplashScreen.tsx
  components/shared/query/ErrorBoundary.tsx
  components/ui/button/ButtonBox.tsx
  components/ui/card/CardItem.tsx
  components/ui/card/component/ConfirmedStatus.tsx
  components/ui/card/component/Like.tsx
  components/ui/modal/datePicker/CustomInput.tsx
  components/ui/modal/datePicker/CustomTimeInput.tsx
  components/ui/modal/variants/CreateMeetingModal.tsx
  components/ui/modal/variants/ProfileModal.tsx
  components/ui/review/ReviewItem.tsx
  eslint.config.mjs
  hooks/useAuth.ts
  hooks/useMeetingCreate.ts
  hooks/useMyPage.ts
  hooks/useOptimisticQuery.ts
  package-lock.json
  package.json
  public/sw.js
  public/sw.js.map
  tailwind.config.ts
Labels: optimize

#184 [Feat/api/DOIT-4] 채팅 기능 구현
  api/client/chat/chatApi.ts
  api/socket/websocket.ts
  app/layout.tsx
  app/liked/page.tsx
  app/meeting/list/components/MeetingList.tsx
  app/myprofile/components/MeetingTab.tsx
  app/review/components/ReviewList.tsx
  components/layout/RootLayout.tsx
  components/modal/variants/CreateMeetingModal.tsx
  components/ui/button/ButtonBox.tsx
  components/ui/chatting/ChatMessageList.tsx
  components/ui/chatting/ChattingMessage.tsx
  components/ui/chatting/ChattingModal.tsx
  components/ui/chip/ChipDate.tsx
  components/ui/review/ReviewItem.tsx
  components/utils/WebSocketInitializer.tsx
  hooks/chat/useChatMessages.ts
  hooks/chat/useWebSocket.ts
  hooks/meeting/useJoinLightning.ts
  lib/constants/toast/text/errorText.ts
  lib/constants/toast/text/successText.ts
  package-lock.json
  package.json
  public/assets/chat/chat.svg
  public/assets/chat/send.svg
  store/chat/chatStore.ts
  store/chat/websocketStore.ts
  store/chatStore.ts
  store/user/userStore.ts
  test/unit/utils/formatDateTime.test.ts
  utils/timeUtils/formatDateTime.ts
  utils/timeUtils/formatRelativeTime.ts
Labels: API

#190 [Feat/optimize/landing page/DOIT-105] 회원가입/로그인 페이지 컨패티 효과 추가 & 403 처리
  api/middleware/api.ts
  app/user/component/ConfettiEffect.tsx
  app/user/signin/page.tsx
  app/user/signup/page.tsx
  hooks/user/useSignUp.ts
  hooks/user/useSignin.ts
  package-lock.json
  package.json
Labels: Refactor

#191 [Feat/advanced/chatting/DOIT-111] 채팅 기능 4차 구현
  .github/pull_request_template.md
  api/client/chat/chatApi.ts
  api/client/meeting/joinMeeting.ts
  api/middleware/websocketMiddleware.ts
  api/socket/websocket.ts
  app/meeting/detail/[id]/@bottombar/page.tsx
  components/chatting/ChatMessageList.tsx
  components/chatting/ChattingMessage.tsx
  components/chatting/ChattingModal.tsx
  components/layout/RootLayout.tsx
  components/ui/card/CardItem.tsx
  hooks/chat/useChatMessages.ts
  hooks/chat/useWebSocket.ts
  lib/constants/toast/text/errorText.ts
  store/chat/websocketStore.ts
  store/profileStore.ts
Labels: optimize

#192 [Feat/optimize/chatting/DOIT-112]
  lighthouserc.json
  next-sitemap.config.js
  next.config.ts
  package-lock.json
  package.json
  public/robots.txt
  public/sitemap.xml
  public/sw.js
  public/sw.js.map
Labels: optimize

#189 [feat/api/mypage/DOIT-86-fix2] hotfix: 마이페이지 반응형 일부 수정
  app/myprofile/components/MeetingTab.tsx
  app/myprofile/components/ReviewTab.tsx
  public/sw.js
  public/sw.js.map
Labels: bug

#196 [Feat/api/mypage/DOIT-86 fix2] myProfile페이지 리팩토링
  app/myprofile/@meeting/page.tsx
  app/myprofile/components/ActivityFilter.tsx
  app/myprofile/components/InfiniteScrollLoader.tsx
  app/myprofile/components/MeetingCard.tsx
  app/myprofile/components/MeetingContainer.tsx
  app/myprofile/components/MeetingTab.tsx
  app/myprofile/components/MeetingTabHeader.tsx
  app/myprofile/components/ReviewCard.tsx
  app/myprofile/components/ReviewContainer.tsx
  app/myprofile/components/ReviewTab.tsx
  app/myprofile/components/StateComponents.tsx
  hooks/myPage/useMyPageState.ts
  public/sw.js
  public/sw.js.map
  types/myPage/myPage.ts
Labels: Refactor
